Added Moja global's Branding Guidelines
moja-global/community-website pull request #207
Opened 2021-11-03 11:33 UTC by vedant-kakde

Signed-off-by: Vedant Kakde <69970950+vedant-kakde@users.noreply.github.com>

## Description

Added Moja global's new branding guidelines on community-website.

## Type of change

- [x] This change requires a documentation update.

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2021-11-06 09:34 UTC, HarshCasper requested changes
Round-1 Review

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +## Logomarks
Give a line break between headings.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/social-media-and-training-platforms.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/presentations-and-data-visualizations.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/digital-correspondence.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/printed-stationery.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/outdoor-marketing.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/website-1.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/website.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/imagery.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/color-gradients.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/color-palette.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +## Color
Give a line break after headings

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/typographic-hierarchy.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/typographic-families.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/outdoor-marketing.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/placement-and-usage.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/graphic-gradients.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/graphic-elements.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-06 09:34 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +<img src="/img/brand/logomark-misuse.png"/>
Provide proper alt text and use an image caption. Refer `Moja global's mission` to know how it is done.

2021-11-12 05:29 UTC, HarshCasper requested changes

2021-11-12 05:29 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +## Logomark Usage
Give a line break between headings

2021-11-12 05:29 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +### Primary Logomark
`Logomark` should be in smallcase. Headings should always have the first character in the uppercase alone.

2021-11-12 05:29 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +#### Monochromatic Usage
Replace `Usage` with `usage`

2021-11-12 05:29 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +### Secondary Logomark
Replace `Logomark` with `logomark`

2021-11-12 05:29 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +Shown here is the secondary Moja Global logomark.
Replace `Global` with `global` and `Moja` with `moja`

2021-11-12 05:29 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +| Secondary Colorway 2A - is to be used in instances where a white/light colored background and/or a light colored image is present.      | <img src="/img/brand/secondary-logomark-2a.png" alt="second
The alt-text should be descriptive of the image itself. Some of the alt-text you wrote is quite good and could even be incorporated into the text, but it needs to be reformulated into actual alt-text for the images. [Here's a nice guide about writing alt-text](https://webaim.org/techniques/alttext/).

2021-11-12 05:29 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +Do's and Don'ts
Remove this line

2021-11-12 05:29 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +## Graphic Elements
Give a line break

2021-11-12 05:29 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +Do not:
Use full sentences

2021-11-12 05:29 UTC, HarshCasper commented on website/docs/02-About/3-branding.mdx
> +
Remove the extra line

2021-11-15 09:19 UTC, sohamsshah commented
Hey @vedant-kakde , are you working on this?

2021-11-15 09:21 UTC, vedant-kakde commented
@sohamsshah Yes. Please allow me some time.

2021-11-15 09:27 UTC, sohamsshah commented
> @sohamsshah Yes. Please allow me some time.

Sure! Please take your time. Just was asking as a follow-up :)

2021-11-28 03:56 UTC, helper-uttam approved these changes

2021-12-23 04:36 UTC, HarshCasper approved these changes

2021-12-23 04:36 UTC, merged

2021-12-23 07:40 UTC, vedant-kakde commented
Thanks @HarshCasper !