Made changes to the UI of footer and sponsors section
moja-global/community-website pull request #253
Opened 2021-12-17 08:32 UTC by khush2706

# Pull Request Template

## Description

- Changed the layout of sponsors section and made it responsive.
- Swizzled the footer code.
- Changed the layout of the footer section.
- Added social icons for links in the footer.
- Made footer Responsive.
- Removed irrelevant links from the footer.

Fixes # (issue)
#228 

Please delete options that are not relevant.

- [ x ] Bug fix (non-breaking change which fixes an issue).

...

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ x ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2021-12-18 06:10 UTC, sohamsshah commented
Hey @khush2706 , can you please post screenshots of the UI changes done?

2021-12-18 06:37 UTC, khush2706 commented
> Hey @khush2706 , can you please post screenshots of the UI changes done?

I have changed the footer UI from this:
![Desktop view](https://user-images.githubusercontent.com/86849664/146631813-783e1dcb-b693-43c2-92c2-8187ac448d9c.png)

![Mobile view](https://user-images.githubusercontent.com/86849664/146631853-d92112b3-c649-4171-8c9d-e017bd5c4ffd.jpeg)

To this:
![image](https://user-images.githubusercontent.com/86849664/146631881-1d483e19-2bc3-4922-8480-ae59dd8f48ad.png)

![image](https://user-images.githubusercontent.com/86849664/146631895-f467193e-101b-4766-89e9-8db64b37dcb7.png)

And the mobile view of Sponsors section from this:
![image](https://user-images.githubusercontent.com/86849664/146631938-dc2579a0-7e4e-4740-aa6c-ec6766b1ab47.png)

To this:
![image](https://user-images.githubusercontent.com/86849664/146631969-0d3d3fa6-f8af-4676-9694-f173b1f95309.png)

2021-12-22 21:22 UTC, sohamsshah requested changes
Hey @khush2706 , thanks for working on this! I have suggested some minor changes in the implementation.

Few changes: 
![image](https://user-images.githubusercontent.com/47717492/147156436-97aba54e-6688-4a5b-a299-3e30e7ab3c2b.png)4

Can we remove the horizontal line and increase the font-size back to the previous size to the `copyright` text?

- The icons under the `Follow Us` title has a small left margin which leads the icons to misalign with the title text. Should be a simple fix.

After that this PR is good to be merged. Feel free to ping if you have any blockers.

2021-12-22 21:22 UTC, sohamsshah commented on website/docusaurus.config.js
> +              <img class="socials" src="/img/twitter.png" />
Can we have `alt` attribute on the img tags for better accessibility?

2021-12-22 21:22 UTC, sohamsshah commented on website/src/theme/Footer/index.js
> + * Copyright (c) Facebook, Inc. and its affiliates.
Remove these comment lines relating to Facebook Inc.

2021-12-22 21:22 UTC, sohamsshah commented on website/src/theme/Footer/styles.module.css
> + * Copyright (c) Facebook, Inc. and its affiliates.
Please remove these comments as well

2021-12-23 13:17 UTC, khush2706 commented
@sohamsshah I have made the suggested changes. Kindly check it.

2021-12-23 14:42 UTC, sohamsshah approved these changes
LGTM! Thanks @khush2706 for the contribution! 🎉

2021-12-23 14:42 UTC, merged

2022-01-11 09:38 UTC, HarshCasper commented
@all-contributors bot please add @khush2706 for code