added counter data UI
moja-global/community-website pull request #262
Opened 2021-12-29 08:18 UTC by wasp0094

Signed-off-by: wasp0094 <90551491+wasp0094@users.noreply.github.com>

# Pull Request Template

## Description

Added static data for the animated counter and animated hover effect in the contributors component. It is responsive on small screens and supports dark mode.

Fixes #254 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality).

## Additional Context (Please include any Screenshots/gifs if relevant)

![Screenshot (179)](https://user-images.githubusercontent.com/90551491/147640245-7be55b12-44a0-49e9-a3f7-9f3386f9ca6e.png)
light mode.

![Screenshot (180)](https://user-images.githubusercontent.com/90551491/147640291-98106cff-86f3-42d3-a694-f00780a88cab.png)
dark mode.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2021-12-30 07:12 UTC, padmajabhol requested changes
Can we improve the UI a bit? Not talking about the hover effect here. Maybe we can make it similar to how it is in the sponsor's section.

Also, keep some padding on the top.

2021-12-30 09:04 UTC, wasp0094 commented
> Can we improve the UI a bit? Not talking about the hover effect here. Maybe we can make it similar to how it is in the sponsor's section.
> 
> Also, keep some padding on the top.

sure, I'll see to it 👍

2021-12-30 12:51 UTC, wasp0094 commented
improved the UI as requested, it now looks like this:
![Screenshot (181)](https://user-images.githubusercontent.com/90551491/147753491-0b153e62-e176-435d-a6fb-8b110bae4a6e.png)
dark mode.

![Screenshot (182)](https://user-images.githubusercontent.com/90551491/147753507-85b484a2-0aa2-4d37-aff5-4296f0ef2980.png)
light mode.

2022-01-01 08:40 UTC, padmajabhol requested changes
The data isn't accurate. Change 30+ contributors to 40+, forks to 80+ , 120+ PRs,  40+ stars.

2022-01-01 11:32 UTC, sohamsshah requested changes
Hey @wasp0094 , great work with the UI. I see that the stars, contributors, PRs etc. data are static content and aren't updated automatically.

Can you come up with dynamic updation of this data via API or some similar technique?

2022-01-01 14:42 UTC, padmajabhol commented
You can use the Github API to make the calls, though I think this will require parsing. Considering you are a beginner, you can always ask @sohamsshah or me on how to work through this issue if you aren't sure or we can create another issue to make the data dynamic.  For reference : https://gist.github.com/jasonrudolph/6057563

2022-01-04 08:53 UTC, padmajabhol commented on website/src/css/custom.css
> +}
Can you resolve the conflicts on this particular file?

2022-01-09 16:59 UTC, sohamsshah commented
Hey @wasp0094 , any updates on this PR? Please feel free to reach out if you are facing any friction in implementing this.

2022-01-10 08:05 UTC, wasp0094 commented
hi, yes i'm still working on it and discussed it with @padmajabhol

2022-01-10 08:45 UTC, sohamsshah commented
Awesome @wasp0094 ! 🚀

2022-01-10 15:52 UTC, closed without merging