Changed UI of Roadmap Page
moja-global/community-website pull request #263
Opened 2021-12-30 13:07 UTC by khush2706

## Description

I have changed the UI and layout of the Roadmaps page. I have changed the UI of project cards as well as of the modal wrapper.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).

## Additional Context (Please include any Screenshots/gifs if relevant)
![image](https://user-images.githubusercontent.com/86849664/147754049-1f9e22e9-dfaf-4455-b1c5-43b48040c1a5.png)

![image](https://user-images.githubusercontent.com/86849664/147754104-08cbaac4-d743-4054-99e4-fdd71942d200.png)

![image](https://user-images.githubusercontent.com/86849664/147754141-d015f827-2b0a-433a-b07a-5178b2ed0f02.png)

![image](https://user-images.githubusercontent.com/86849664/147754374-7d6c18f8-92c1-4b6e-b026-e017b6fcdf80.png)

![image](https://user-images.githubusercontent.com/86849664/147754412-8ef86110-9f69-4076-9f33-fe7d1379849c.png)

![image](https://user-images.githubusercontent.com/86849664/147754472-99635449-4336-474d-95d9-05f507d53c87.png)

![image](https://user-images.githubusercontent.com/86849664/147754501-6c18db7f-277c-4478-9aca-6d1ecf401c5d.png)

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2021-12-30 13:10 UTC, khush2706 commented
@HarshCasper can you please review my pull request.

2022-01-05 18:32 UTC, sarthakkundra commented
Resolved the conflicts @khush2706 @HarshCasper  :)

2022-01-05 18:35 UTC, sarthakkundra requested changes

2022-01-05 18:35 UTC, sarthakkundra commented on website/src/pages/ProjectCard/ProjectCard.js
> +        {/* <div className="modal_links">
remove the commented out code if not required

2022-01-05 18:35 UTC, sarthakkundra commented on website/src/pages/ProjectCard/card.css
> +  /* width: 500px;
we have classes for this in tailwind CSS. Please use that. Also remove the commented out code

2022-01-05 18:35 UTC, sarthakkundra commented on website/src/pages/ProjectCard/card.css
> +  /* text-decoration: underline;
remove comment. Use Tailwind

2022-01-05 18:37 UTC, sarthakkundra commented
@khush2706 I see a lot of new CSS being written. While the UI looks good, I think we can achieve the same result with Tailwind CSS as well which is already configured in the project. This will also boost the performance of the website since the overall bundle size would be lesser. I'll appreciate it if you can do that. Thank you for contributing to moja global 💯

2022-01-07 15:42 UTC, khush2706 commented
@sarthakkundra I've made the suggested changes, can you pls review my PR again...also, there are a few things I need help with, I've messaged you on slack regarding the same :)

2022-01-20 06:10 UTC, sohamsshah requested changes
Hi @khush2706 , this PR looks great, awesome work. I have made few refactors in the code, you can have a look. Also, I have few suggestions that you can work upon this.

In the `ProjectCard.js` file, there are a lot of different components being used and are repetitive. We can create small components for them and use them in the ProjectCard.

Moreover, `handleClick` function uses `document.querySelector` DOM Api. In React Apps, it is not a good practice to directly change state and this may cause side effects. Can you come up with a `state`-based solution for handling this? We can brainstorm upon this if you want. Let me know if I can help anywhere in this.

2022-01-20 06:42 UTC, khush2706 commented
> Hi @khush2706 , this PR looks great, awesome work. I have made few refactors in the code, you can have a look. Also, I have few suggestions that you can work upon this.
> 
> In the `ProjectCard.js` file, there are a lot of different components being used and are repetitive. We can create small components for them and use them in the ProjectCard.
> 
> Moreover, `handleClick` function uses `document.querySelector` DOM Api. In React Apps, it is not a good practice to directly change state and this may cause side effects. Can you come up with a `state`-based solution for handling this? We can brainstorm upon this if you want. Let me know if I can help anywhere in this.

Sure! I'll make components for the timeline divs. As for the state-based solution, I'll try and see if I could make it work and I'll make sure to ask you if I get stuck anywhere.

2022-01-27 09:56 UTC, HarshCasper approved these changes

2022-01-27 09:59 UTC, HarshCasper commented
@sohamsshah Let's follow up with the refactor part after this PR gets merged. This is way too awesome work @khush2706 and I'm glad that you pulled this off! Thanks a lot for your contributions 🎉

2022-01-27 09:59 UTC, merged