Added a new calendar for Moja Global Community Website
moja-global/community-website pull request #272
Opened 2022-01-10 11:46 UTC by Palaksharma23

I have added a calendar for meetings section of moja-global Community website using react big calendar module

2022-01-10 11:46 UTC, Palaksharma23 commented
@HarshCasper @sohamsshah sir can you please once review it .

2022-01-11 04:36 UTC, sohamsshah requested changes
Great work @Palaksharma23 . I have suggested few changes, otherwise the PR looks good.

Before merging this, we can do a small research around embedding `Google Calendar` to the project (assuming the Google Calendar of Moja Global would be public, shareable and open for anyone who wants to join.) The embed is a typical `iframe` and also the theme and other actions can be updated.

If the embed works satisfactorily, we can consider this alternative over `react-big-calendar` to avoid an external dependency and overhead of updating meeting schedule manually on the website.

Refer: https://support.google.com/calendar/answer/41207

Cc: @HarshCasper

2022-01-11 04:36 UTC, sohamsshah commented on website/src/pages/initiatives.js
> +  window.open('https://workspace.google.com/intl/en_in/products/calendar/?utm_source=google&utm_medium=cpc&utm_campaign=1011352-Workspace-APAC-IN-en-BKWS-EXA-Golden&utm_content=text-ad-none-none-DEV_
This Link should take the user to the corresponding event in google calendar. Need to replace this google calendar **meeting** link for Moja Global. We can export this static data from the `websiteData/meetings.js` folder. 

Alternatively, if we can find some way to link a particular meeting from the google calendar, we can take the data from the events.obj from `websiteData/meetings.js`

2022-01-11 04:36 UTC, sohamsshah commented on website/src/pages/initiatives.js
> +                <a href="https://workspace.google.com/intl/en_in/products/calendar/?utm_source=google&utm_medium=cpc&utm_campaign=1011352-Workspace-APAC-IN-en-BKWS-EXA-Golden&utm_content=text-ad-none
Need to replace this google calendar link for Moja Global. We can export this static data from the `websiteData/meetings.js` folder.

2022-01-11 04:36 UTC, sohamsshah commented on website/src/pages/initiatives.js
> +function ondouleclick() {
Please rename this function as `onDoubleClick()`

2022-02-12 19:23 UTC, sohamsshah commented
Meetings Section now looks like:
![image](https://user-images.githubusercontent.com/47717492/153725319-af5a4ec8-809d-41a0-b2c4-f21c976a2d8c.png)

We can add the meetings inside `websiteData/meetings.js`. Have added comments on how to add a meeting.

2022-02-13 05:12 UTC, HarshCasper approved these changes
Cool work @Palaksharma23 and @sohamsshah 🎉 

LGTM!

2022-02-13 05:13 UTC, merged