My Outreachy Experience Blog
moja-global/community-website pull request #309
Opened 2022-03-08 09:51 UTC by asmijafar20

# Pull Request Template

## Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2022-03-10 22:30 UTC, iamrajiv requested changes
@asmijafar20 Check my suggested changes.

2022-03-10 22:30 UTC, iamrajiv commented on website/blog/2022-03-07-outreachy-blog.md
> +Lastly, I want to extend my gratitude to the Moja Global community and decided to Mentor for Google Summer of Code 2022. And I want to thank [Andrew O'Reilly-Nugent](https://github.com/aornugent) and
```suggestion
---
title: Outreachy Blogs
image: https://dev-to-uploads.s3.amazonaws.com/uploads/articles/3b4xdim2k09gg085gwse.png
---

# My Outreachy internship experience blog - Asmi Jafar

I have started my open source journey with an Outreachy internship only. I was a complete beginner in open source when I started contributing to the Moja Global community and it turns out to be my selection as an Outreachy intern with Moja Global. I never participated in any open-source program previously but got an opportunity with Outreachy to showcase my interest. And in these past three months, I have learned a lot of new things and implemented them as well.

I started with good first issues with Moja Global, updated links and versions across repositories. Later, I contributed to the community website by adding the feature for displaying all Contributors during the Outreachy contribution period. Lastly, I have finished all the tasks given to participants to showcase their skills during my contribution period.

Over the past three months, I have been working with [Harsh Mishra](https://github.com/HarshCasper) on implementing Continuous Integration and Delivery (CI/CD) pipelines across the Moja Global repositories and centralizing the Moja Global docker images on the GitHub Container Registry. I have worked with [Anthony Kwaje](https://github.com/Tonnix) on FLINT Reporting Tool with 31 Microservices! And this blog would be documenting my experience and the project report.

<h3>About Project:</h3>

[Moja Global](https://github.com/moja-global) is a non-profit, collaborative project that brings together a community of experts to develop open-source software – including the [FLINT](https://github.com/moja-global/FLINT) – to help users accurately and affordably estimate greenhouse gas emissions and removals from forestry, agriculture and other land uses (AFOLU).

The [FLINT Reporting tool](https://github.com/moja-global/FLINT.Reporting) of Moja global is to provide Business Intelligence for analyzing and transforming FLINT output databases into useful information and outputs.

The goal of my project was to implement the CI/CD pipelines at Moja global and implement the framework for reproducible research. One of the project parts focuses on the FLINT reporting tool, its maintenance, and assisting to make it more user-friendly. Also implementing the CI/CD pipelines for the reporting tool by using GitHub Actions and making it deployment ready. Along with this the part of the project also targets centralizing and migrating the docker images across the community **GitHub Container Repository**.

<p align="center">
  <img src="https://dev-to-uploads.s3.amazonaws.com/uploads/articles/acqrdrxb4wk7oek2p6da.png"  alt="FLINT Reporting Tool System and Purpose"></img>
  <figcaption><em>Fig: FLINT Reporting Tool System and Purpose</em></figcaption>
</p>

<h3>Goals Achieved:</h3>

**1) Understood the FLINT, FLINT Implementation, and the FLINT Reporting Tool Structure.**

The FLINT is considered as the library itself - it doesn't do much unless we attach modules to it and make it an implementation. FLINT implementations extend the FLINT library image and the library image extends the FLINT base image. In our case for the FLINT implementation image, we have used **SLEEK** (_Standard Land emissions and extractions of Kenya_) image. Later the outputs are used as the FLINT application image i.e. Reporting Tool images.

<p align="center">
  <img src="https://dev-to-uploads.s3.amazonaws.com/uploads/articles/dvwru1debotkgl6u23ef.jpg" height="438" width="438"></img>
</p>

**2) Strategized and Centralized Docker images across the community for standardization and uniformity.**

Previously, the Moja Global images were published on the docker hub registry but it wasn’t centralized and maintained for a long time. Also, there are no Continuous integration workflows set up in the [FLINT Cloud](https://github.com/moja-global/FLINT.Cloud) and [FLINT Reporting tool](https://github.com/moja-global/FLINT.Reporting) repository so the images are not able to update when there is a new release in the project. We have built and published all the images using GitHub Actions to the GitHub Container Registry. Now, Moja Global has **30 packages** published on the Moaj Global GitHub Container Registry. It increased the uniformity and accessibility across the community.

<p align="center">
  <img src="https://dev-to-uploads.s3.amazonaws.com/uploads/articles/c0aarfnhpyfw6dhywtys.png"  width="550" alt="Moja Global GitHub Packages"></img>
  <figcaption><em>Fig: Moja Global GitHub Packages</em></figcaption>
</p>

**3) Maintenance and Rectification of the FLINT Reporting tool.**

Worked on maintaining the versions and containerizing the Client of the reporting tool. Later implemented the CI/CD for the front-end build of the tool. The FLINT Reporting tool was built as a spring boot application with **31 microservices**.

We have streamlined the containerization of the reporting tool microservices and implemented the Continuous Integration and Delivery for the same. We have published the docker images of the microservice on the GitHub Container Registry.

The build process for the workflow of the microservices was taking more than 4 mins and later we have optimized the build process by **18x faster** by using **Docker caching method**.

<p align="center">
  <img src="https://dev-to-uploads.s3.amazonaws.com/uploads/articles/trmi2anmxy6y7xrm91qh.png" width="550"></img>
    <figcaption><em>Fig: Reporting tool Microservices workflow.</em></figcaption>
</p>

**4) Setup the FLINT reporting Kubernetes environment and automate the process for the reporting tool.**

The functionality of the Reporting Tool is delivered using a **Microservice-based** architecture. While this was inspired by the many benefits that the architecture provides, the primary motivation was the need to scale different parts of the system independent of each other.
It comprises 31 microservices and **Spring Webflux** was chosen as the framework to implement the Reporting Tool Microservices. And the Reporting Tool’s User interface is implemented using **Angular** which blends beautifully with the rest of the microservice stack.

The Reporting Tool system has a collection of scripts that have been designed for use in the setup of its environment. We have streamlined and automated the process by creating one superscript for all the scripts, which made the process very feasible and developer-friendly.

The Reporting Tool’s **Database** hosts all the data tables that are needed by the Reporting Tool that are not already a part of the FLINT’s Flux Output Database. PostgreSQL has been used for the database.

We have streamlined the process of deploying each service on the Kubernetes cluster by updating and rectifying the **helm charts** `values.yml` files. We have fixed the Database and tested it over the cloud.

**Demo Run:**

Setup the **Kubernetes environment** of the reporting tool on the cloud. First, we install all the dependencies/packages using superscript, then we set up the system by initializing the database and after that deploy services on that using scripts, and finally building a client over that.

The back-end of reporting tool i.e database and services are running efficiently and successfully!

<p align="center">
  <img src="https://dev-to-uploads.s3.amazonaws.com/uploads/articles/7qlzfjvtkfw8eltqnara.png"  width="550" alt="Microservices running at backend"></img>
  <figcaption><em>Fig: Microservices running at backend</em></figcaption>
</p>

<p align="center">
  <img src="https://dev-to-uploads.s3.amazonaws.com/uploads/articles/fgugh9v9m2mmg4rawshb.png"  width="550" alt="Reporting Tool Client"></img>
  <figcaption><em>Fig: Reporting Tool Client</em></figcaption>
</p>

#### You can find my Outreachy internship Week-Wise logs [here.](https://docs.google.com/document/d/17SyTeOY2c9Z6FUE3d7NEG4SlqHmhfIFJOqOVT1kbQ0E/edit?usp=sharing)

<h3>Learnin [...]

2022-03-19 06:40 UTC, HarshCasper approved these changes

2022-03-19 07:54 UTC, aornugent commented
Nice one @asmijafar20! Thanks for your effort!

2022-03-19 07:55 UTC, aornugent approved these changes

2022-03-19 08:42 UTC, merged