fix:incorrect url in editUrl field
moja-global/community-website pull request #325
Opened 2022-04-14 09:31 UTC by tanay123456789

Fixes #317 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2022-04-14 09:35 UTC, tanay123456789 commented
@padmajabhol @Palaksharma23 both of you approved my last PR. I opened this PR again because I messed up with my previously forked repository by which that PR got closed automatically. Sorry for the inconvenience.

2022-04-14 10:04 UTC, Palaksharma23 approved these changes
No worries @tanay123456789 :)

2022-04-21 17:13 UTC, padmajabhol approved these changes

2022-05-08 19:52 UTC, padmajabhol requested changes

2022-05-08 19:52 UTC, padmajabhol commented on website/docusaurus.config.js
> +          editUrl: 'https://github.com/moja-global/community-website/edit/main/website/blog/',
I don't think this is working, leads to 404, please change this to `https://github.com/moja-global/community-website/blog/main/website/` and the `editUrl` of `blog` to `https://github.com/moja-global/community-website/docs/main/website/`

2022-05-12 08:26 UTC, merged