Added new feature to give feedback for community website
moja-global/community-website pull request #327
Opened 2022-04-27 04:31 UTC by Palaksharma23

# Pull Request Template

## Description

I have added a floating icon for taking feedback from users, clicking on the feedback icon will lead users to a feedback form whose value you can check being updated in this API. 

https://sheet.best/api/sheets/3b6fc57e-5cd4-4fbf-b9de-4a58a8d93968

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [✅ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## Additional Context (Please include any Screenshots/gifs if relevant)

...

https://user-images.githubusercontent.com/87171452/165440969-6dccca65-20c9-4fb8-a802-9ad2430e0645.mp4

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

@HarshCasper may you please review this pull request :)

2022-05-05 17:46 UTC, padmajabhol requested changes

2022-05-06 12:11 UTC, Palaksharma23 commented
thank you @padmajabhol i will do the required changes :)

2022-05-08 19:25 UTC, padmajabhol reviewed
Also is there a way you can improve the feedback button's UI? Sorry for the last review, was caught up.

2022-05-08 19:25 UTC, padmajabhol commented on website/src/theme/Footer/index.js
> +    console.log(e.target.value);
Do we need this?

2022-05-08 19:25 UTC, padmajabhol commented on website/src/theme/Footer/index.js
> +    console.log(feedback);
I don't think we need console.log to go into production.

2022-05-11 17:40 UTC, Palaksharma23 commented
sure @padmajabhol :) i will do the required changes

2022-07-07 02:13 UTC, closed without merging