Updated Demodays Page
moja-global/community-website pull request #379
Opened 2022-12-24 11:49 UTC by thisiskaransgit

# Pull Request Template

## Description

Updated Demodays page with the new keynote speakers and details

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [X] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2022-12-24 12:15 UTC, Namyalg commented
Thank you for this @thisiskaransgit 
The section for the LFX mentees looks great !

2022-12-29 12:34 UTC, HarshCasper requested changes
Here is a high-level review:

- Can we change `demodays` to something more useful? Perhaps, something that signifies the mentees we will host over the years which someone can navigate across by click on respective years (like `2022`) ? 
- For @SanjaySinghRajpoot, I would recommend having a more professional picture in place.
- `Agenda` and `What to expect` can be mentioned in a brief box.
- @Namyalg Do we have the recordings hosted somewhere so that we can link it here, please?
- All of the mentee descriptions should be professional and in third person. Can it be standardized?

2022-12-29 12:34 UTC, HarshCasper commented on website/src/pages/demodays.js
> +              their work and learnings with the community.
- Change to `graduated mentees`
- Keep a space between the terms and their abbreviation

2023-02-17 19:47 UTC, thisiskaransgit commented
Hey @HarshCasper, sorry for the pretty late update, I resolved the changes and the resolved merge conflicts too, we will plan to implement the reviews that you mentioned, for now, could you kindly merge the PR, I don't want it to be closed 😓 ?

2023-04-15 01:52 UTC, closed without merging